name: nws2
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite:
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_share: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0


flutter:

 
  uses-material-design: true
